### ISSUE TITLE
 发现一个问题：chatgpt返回字符不会自动格式化，带代码的回复比较难看

### ISSUE THREAD

**Issue by gygy** [dotmet/chatgpt_webui#2]
![image](https://user-images.githubusercontent.com/2096830/219908083-163dd122-dd7f-463b-ac48-0468bfe82e9e.png)

**Comment by dotmet** [comment]
Solved.

![Capture](https://user-images.githubusercontent.com/72541408/219935717-0dd11e95-1bbe-4caf-ae47-fcd28baec97f.JPG)

**Comment by gygy** [comment]
此前不分行。现在输出能自动了，非常好。
