### ISSUE TITLE
输入框输入“问题”后，点击“send”，能否自动清空上次输入的文字及用回车触发？

### ISSUE THREAD

**Issue by gygy** [dotmet/chatgpt_webui#3]
提2个不是问题的小建议：
    1. 能否在输入框输入“问题”，点击发送“send”后，自动将“问题”清空。 目前每次需要手工删除上次的问题。
    2. gr.Button("SEND")，这个事件能否 可以同时用 “回车” 触发，即可点击发送，也可以用回车触发？

  
    message = gr.Textbox(placeholder="Chat here")
    state = gr.State()
    submit = gr.Button("SEND")

**Comment by dotmet** [comment]
已添加回车发送，同时清空输入的功能，

**Comment by gygy** [comment]
手机和PC已测试，更加方便了

**Comment by gygy** [comment]
> 已添加回车发送，同时清空输入的功能，

还有一处问题：
回车 会清空。 但点击“SEND”不会清空。 回车和通过鼠标点击“SEND”效果应一样。

**Comment by dotmet** [comment]
> > 已添加回车发送，同时清空输入的功能，
> 
> 还有一处问题： 回车 会清空。 但点击“SEND”不会清空。 回车和通过鼠标点击“SEND”效果应一样。

已解决

**Comment by gygy** [comment]
解决了
