### ISSUE TITLE
手机浏览页面自适应，看看是否调整下？

### ISSUE THREAD

**Issue by gygy** [dotmet/chatgpt_webui#5]
如下图：
1.   标注1和3的空白太多。 建议： Start Chatting ..  和 h1 那个标题之间的空间尽量压缩；human 和 send 两处，可以直接到底部。这样的好处是 让chatbot回复的那个框足够长。
2. 让标注2 再足够长。主要标注2 是gpt回复区，每次回复的内容都比较多，每次都要滚动。截屏也很难截完整。 让标注2 尽量长一点会好一点。
3. 标注1、2、3区域，尽量让2区域长一点，需手机自适应

下面是手机的目前截图
![1b564a1d16b6595a69b121c03fca461](https://user-images.githubusercontent.com/2096830/219975011-84f20f04-d4aa-4afe-aed3-474bd8f0bf07.jpg)

**Comment by dotmet** [comment]
启动```app.py```时，添加```--no_markdown```参数即可不显示聊天框以外的文字。

**Comment by gygy** [comment]
> 启动```app.py```时，添加```--no_markdown```参数即可不显示聊天框以外的文字。

顶部可以了。底部还是有问题。底部还有很大空间，占手机屏幕快1/3是空白的，中间chatgpt区域没充分利用。。

**Comment by dotmet** [comment]
> > 启动```app.py```时，添加```--no_markdown```参数即可不显示聊天框以外的文字。
> 
> 顶部可以了。底部还是有问题。底部还有很大空间，占手机屏幕快1/3是空白的，中间chatgpt区域没充分利用。。
> 

聊天自动就展开了
![image](https://user-images.githubusercontent.com/72541408/220142484-b43a5eff-6727-4a02-97f6-cbf95432c4c3.png)

**Comment by gygy** [comment]
验证了下，不知道是不是和手机有关。我手机不会自动展开。

**Comment by gygy** [comment]
用最新代码，只添加了用户、密码及session信息
重新测试了下：安卓13，edge浏览器 及 三星浏览器，效果如下：
注意send和底部还有很大空白。上面chatbot回复区 下面还有很长回复内容，不会自动展开的。
![fe631b416af31829b9bdbc01c16edda](https://user-images.githubusercontent.com/2096830/220461484-9a16fda4-b30b-41aa-be49-7ddb0caa5c7b.jpg)

**Comment by dotmet** [comment]
现在可以通过style.css调节聊天窗口高度，默认设置为70vh
