### ISSUE TITLE
webui大可不必,我期望大佬直接做成api接口封装

### ISSUE THREAD

**Issue by lozn00** [dotmet/chatgpt_webui#8]
我直接在其他地方调用就行

**Comment by dotmet** [comment]
直接调接口很难用的，我就是从直接调接口转到使用UI的，手机电脑都可以很方便使用，包括截图也方便。API这块[revChatGPT](https://github.com/acheong08/ChatGPT)就比较好了。

**Comment by lozn00** [comment]
api已经做好了嘛?在哪里,revchatgpt不是纯调用的api服务器啊,我需要启动一个服务器,然后手机端app机器人调用就行了 ,你这网页适用范围太那个了,api可以做更多事情&nbsp;


LoveZ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 中午11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotmet/chatgpt_webui] webui大可不必,我期望大佬直接做成api接口封装 (Issue #8)





 
直接调接口很难用的，我就是从直接调接口转到使用UI的，手机电脑都可以很方便使用，包括截图也方便。API这块revChatGPT就比较好了。

**Comment by dotmet** [comment]
搭建chatgpt sever在github上应该有成熟的项目吧，我这个项目的初衷是利用Hugging face解决访问限制的问题，很多VPN直接访问官网经常抽风，如果使用的VPN稳定的话，是完全不需要用这个轻量UI的。

**Comment by lozn00** [comment]
好的谢谢,我不会找,找不到

&nbsp;


LoveZ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月2日(星期四) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dotmet/chatgpt_webui] webui大可不必,我期望大佬直接做成api接口封装 (Issue #8)





 
搭建chatgpt sever在github上应该有成熟的项目吧，我这个项目的初衷是利用Hugging face解决访问限制的问题，很多VPN直接访问官网经常抽风，如果使用的VPN稳定的话，是完全不需要用这个轻量UI的。
